services:
  - type: web
    name: homelink
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn homelink.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: homelink.settings